# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_outliers_from_dist <- function(dist_, loop_k, loop_lambda, loop_threshold, outlier_on) {
    .Call('_recombine_get_outliers_from_dist', PACKAGE = 'recombine', dist_, loop_k, loop_lambda, loop_threshold, outlier_on)
}

get_outliers_from_ds <- function(ds_, loop_k, loop_lambda, loop_threshold, outlier_on) {
    .Call('_recombine_get_outliers_from_ds', PACKAGE = 'recombine', ds_, loop_k, loop_lambda, loop_threshold, outlier_on)
}

SHC_lasso_getuw <- function(ds_, wbounds_, max_iter, init_random, silent, warm_start) {
    .Call('_recombine_SHC_lasso_getuw', PACKAGE = 'recombine', ds_, wbounds_, max_iter, init_random, silent, warm_start)
}

SHC_lasso_lagrange_getuw <- function(ds_, lambdas_, max_iter, init_random, silent, warm_start) {
    .Call('_recombine_SHC_lasso_lagrange_getuw', PACKAGE = 'recombine', ds_, lambdas_, max_iter, init_random, silent, warm_start)
}

SHC_FL_getuw <- function(ds_, lambda1s_, lambda2s_, max_iter, init_random, silent) {
    .Call('_recombine_SHC_FL_getuw', PACKAGE = 'recombine', ds_, lambda1s_, lambda2s_, max_iter, init_random, silent)
}

SHC_SSL_getuw <- function(ds_, penalty_, lambda1, lambda0s_, theta, aa, bb, eps, max_iter, init_random, silent, warm_start) {
    .Call('_recombine_SHC_SSL_getuw', PACKAGE = 'recombine', ds_, penalty_, lambda1, lambda0s_, theta, aa, bb, eps, max_iter, init_random, silent, warm_start)
}

SHC_get_crit <- function(ds_, w_) {
    .Call('_recombine_SHC_get_crit', PACKAGE = 'recombine', ds_, w_)
}

SHC_get_u <- function(ds_, w_) {
    .Call('_recombine_SHC_get_u', PACKAGE = 'recombine', ds_, w_)
}

multfun <- function(x_) {
    .Call('_recombine_multfun', PACKAGE = 'recombine', x_)
}

distfun <- function(x_) {
    .Call('_recombine_distfun', PACKAGE = 'recombine', x_)
}

